export const FILE_QUEUE = 'process_file_queue'
export const FILE_QUEUE_CONSUMER = 'process_file_queue_consumer'
export const CATEGORY_QUEUE = 'process_category_queue'
export const CATEGORY_QUEUE_CONSUMER = 'process_category_queue_consumer'
export const DECK_QUEUE = 'process_deck_queue'
export const DECK_QUEUE_CONSUMER = 'process_deck_queue_consumer'
